/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include"Reg.h"
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
volatile RC_reg* RCC_CR = (volatile RC_reg*)0x40021000;
volatile CFGR_reg* RCC_CFGR = (volatile CFGR_reg*)(0x40021000+ 0x04);
volatile APB2ENR_reg* RCC_APB2ENR= (volatile APB2ENR_reg* )(0x40021000+ 0x18);
int main(void)
{

	RCC_CR->RC_bits.HSI_ON =1;
	RCC_CFGR->CFGR_bits.PLL_SRC=0;				//0: HSI oscillator clock / 2 selected as PLL input clock
	RCC_CFGR->CFGR_bits.PLL_MUL= 0b0110;		//0110: PLL input clock x 8
	RCC_CFGR->CFGR_bits.SW =0b10;				//10: PLL selected as system clock
	RCC_CR->RC_bits.PLL_ON = 1;					//1: PLL ON
	RCC_CFGR->CFGR_bits.HPRE=0;					//0xxx: SYSCLK not divided
	RCC_CFGR->CFGR_bits.PPRE1 =0b100;			//100: HCLK divided by 2
	RCC_CFGR->CFGR_bits.PPRE2 =0b101;			//101: HCLK divided by 4
	RCC_APB2ENR->APB2ENR_bits.IOPA_EN=1;

	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}

