/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include"Reg.h"

#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
//#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)
//#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
volatile GPIO_IDR_reg* GPIOA_IDR = (volatile GPIO_IDR_reg*)(GPIOA_BASE+0x08);

#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
//#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)
//#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
volatile GPIO_ODR_reg* GPIOB_ODR = (volatile GPIO_ODR_reg*)(GPIOB_BASE+0x0C);


volatile APB2ENR_reg* RCC_APB2ENR= (volatile APB2ENR_reg* )(0x40021000+ 0x18);



void my_delay(int d){
	int i,j;
	for(i=0; i<d;i++)
		for(j=0;j<d;j++);
}
int main(void)
{

	SystemClock_init();
	GPIO_init();

	while(1){
		if(GPIOA_IDR->IDR_bits.IDR1 == 0){
			GPIOB_ODR->ODR_bits.ODR1 ^=1;
			while(GPIOA_IDR->IDR_bits.IDR1 == 0);
		}
		if(GPIOA_IDR->IDR_bits.IDR13 == 1){
			GPIOB_ODR->ODR_bits.ODR13 ^=1;
			my_delay(100);
		}
	}
}

void GPIO_init(void){
	//GPIOA PortA pin1,13 as input floating
	GPIOA_CRL&=~(0b1111 << 4);
	GPIOA_CRL|=(0b0100 << 4);
	GPIOA_CRH &= ~(0b1111 << 20);
	GPIOA_CRH |=(0b0100 << 20);

	//PortB pin 1,13 as output PushPull
	GPIOB_CRL&=~(0b1111 << 4);
	GPIOB_CRL|=(0b0001 << 4);
	GPIOB_CRH &= ~(0b1111 << 20);
	GPIOB_CRH |=(0b0001 << 20);

}

void SystemClock_init(void){
	//RCC_CR->RC_bits.HSI_ON =1;
	//RCC_CFGR->CFGR_bits.SW =0;
	//RCC_CFGR->CFGR_bits.HPRE=0;
	//RCC_CFGR->CFGR_bits.PPRE1 =0;
	//RCC_CFGR->CFGR_bits.PPRE2 =0;
	RCC_APB2ENR->APB2ENR_bits.IOPA_EN=1;	//PORTA clock enable
	RCC_APB2ENR->APB2ENR_bits.IOPB_EN=1;	//PORTB clock enable

}
void EXTI0_IRQHandler(void){
	//Toggle PartA pin 13
	//GPIOA_ODR ^= (1<<13) ;

	//clear Pending
	//EXTI_PR |=(1<<6);
}
