/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F103C6_GPIO_Driver.h"
#include "STM32F103C6_EXTI_Driver.h"
#include <stdint.h>
#include"LCD.h"
#include"keypad.h"
#include "SEG_7.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//void GPIO_init(void){
//	GPIO_PinConfig_t PinConfig;
//	//GPIOA PortA pin1,13 as input floating
//	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
//	PinConfig.GPIO_PinMODE = GPIO_MODE_INPUT_PU;
//	MCAL_GPIO_Init(GPIOA, &PinConfig);
//	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
//	MCAL_GPIO_Init(GPIOA, &PinConfig);
//
//	//PortB pin 1,13 as output PushPull
//	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
//	PinConfig.GPIO_PinMODE = GPIO_MODE_OUTPUT_PP;
//	PinConfig.GPIO_Pin_OutputSpeed= GPIO_SPEED_10M;
//	MCAL_GPIO_Init(GPIOB, &PinConfig);
//	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
//	MCAL_GPIO_Init(GPIOB, &PinConfig);
//}

void SystemClock_init(void){

	RCC_GPIOA_CLK_EN();	//PORTA clock enable
	RCC_GPIOB_CLK_EN();	//PORTB clock enable

}


void my_delay(int d){
	int i,j;
	for(i=0; i<d;i++)
		for(j=0;j<d;j++);
}

int main(void)
{
	EXTI_GPIO_MAPPING_t E = EXTI0PA0;
	//GPIO_init();
	SystemClock_init();
	//LCD Init
	LCD_init();
	LCD_W_str("    LCD READY");
	LCD_clear();
	//7segment init
	SEG_init();
	LCD_W_str("7 SEGMENT READY");
	uint8_t SEG_Numbers[10]={ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE};
	uint8_t i;

	for(i=0;i<10;i++)
	{
		SEG_Write_Number(~SEG_Numbers[9-i]);
		LCD_Set_XY(8, 0);
		LCD_W_char('9'-i);
		my_delay(250);
		LCD_clear();

	}
	Keypad_init();
	char pressedKey;
	//LCD_W_char('k');
	LCD_clear();
	LCD_W_str("  KEYPAD READY");
	LCD_clear();
	while(1){
//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0){
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
//			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
//		}
//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1){
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
//			my_delay(100);
//		}
		pressedKey=Keypad_Getkey();
		if(pressedKey != 'A')
			LCD_W_char(pressedKey);

	}

}


