/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<Platform_Types.h>
#define RCC_BASE 	0x40021000
#define GPIOA_BASE	0x40010800
#define RCC_APB2ENR	*(vuint32*)(RCC_BASE + 0x18)
#define GPIOA_CRH 	*(vuint32*)(GPIOA_BASE + 0x04)
typedef union{
	vuint32 All_Ports;
	struct{
		vuint32 reserved	:13;
		vuint32 pin_13		:1;
	}Reg_pins;
}Reg;

volatile Reg* ODR_R =(volatile Reg*)(GPIOA_BASE + 0x0c);
int main(void)
{
	RCC_APB2ENR |= (1<<2);
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;
	int i;
	while(1){
	ODR_R->Reg_pins.pin_13 =1;
	for(i=0; i<10000;i++);
	ODR_R->Reg_pins.pin_13=0;
	for(i=0; i<10000;i++);
	}
}
